# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 570fca340f73d4990daff231a88745d3979d9b4a0c0d48504ccf90b7a510489e4a676a40668d530789ab51ada2c96d80e3101c345e01e85cf7db8ee26ab02d49

test:
  secret_key_base: 5913873cbc1c92f5ae1be6df3fd4a31538f6d85f24234c371cb8b5b19715b308b3b5176c97a6fcf4f6f0414fb6242be35d37cbe313adaf96c5b60cfe0194e8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
